#Common
label: gitops

#Deployment
replicas: 3
image:
  repository: docker.io/DOCKERHUB_REPO_NAME/gitops-go-app # 変更箇所 DOCKERHUB_REPO_NAME
  tag: 6

imageConfig:
  pullPolicy: IfNotPresent

#Service
service_type: LoadBalancer